services:
  #############################################################################################
  ###                                       BACKEND                                         ###
  #############################################################################################
  playground-express-api:
    container_name: playground-express-api
    tty: true
    init: true # Properly handles running as PID 1 inside a container. Source: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "node", "/app/scripts/healthcheck.js"] # Check health endpoint for healthy service.
      interval: 30s # Perform the health check every 30 seconds.
      timeout: 10s # Consider the health check a failure if it takes more than 10 seconds.
      retries: 5 # Retry the health check up to 5 times before considering the container unhealthy.
    build:
      context: ./src
      dockerfile: ./backend/Dockerfile
      target: prod
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - DEBUG=${DEBUG:-true}
      - PORT=${BACKEND_PORT:-6600}
      - FRONTEND_URL=${FRONTEND_URL:-'http://localhost:6500'}
      - BACKEND_URL=${BACKEND_URL:-'http://localhost:6600'}
      - PGHOST=${DATABASE_HOST:-postgres-database} # Name of the database container.
      - PGUSER=${DATABASE_USER:-postgres}
      - PGPASSWORD=${DATABASE_PASSWORD:-postgres}
      - PGDATABASE=${DATABASE_NAME:-playground}
      - PGPORT=5432
      - SSO_AUTH_SERVER_URL=${SSO_AUTH_SERVER_URL}
      - SSO_CLIENT_ID=${SSO_CLIENT_ID}
      - SSO_CLIENT_SECRET=${SSO_CLIENT_SECRET}
      - SSO_INTEGRATION_ID=${SSO_INTEGRATION_ID}
      - SSO_ENVIRONMENT=${SSO_ENVIRONMENT}
      - CSS_API_CLIENT_ID=${CSS_API_CLIENT_ID}
      - CSS_API_CLIENT_SECRET=${CSS_API_CLIENT_SECRET}
    networks:
      - playground-network
    ports:
      - ${BACKEND_PORT:-6600}:6600
    depends_on:
      playground-postgres-database:
        condition: service_healthy

  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  playground-react-frontend:
    container_name: playground-react-frontend
    tty: true
    restart: on-failure
    build:
      context: ./src/frontend
      target: prod
    networks:
      - playground-network
    ports:
      - ${FRONTEND_PORT:-6500}:6500
    depends_on:
      playground-express-api:
        condition: service_healthy

  #############################################################################################
  ###                                       Database                                        ###
  #############################################################################################
  playground-postgres-database:
    container_name: playground-postgres-database
    tty: true
    image: postgres:16-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-postgres}"] # Check if PostgreSQL is ready.
      interval: 15s # Perform the health check every 15 seconds.
      timeout: 5s # Consider the health check a failure if it takes more than 5 seconds.
      retries: 5 # Retry the health check up to 5 times before considering the container unhealthy.
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-playground}
    networks:
      - playground-network
    ports:
      - ${DATABASE_PORT:-6700}:5432
    volumes:
      - database-data:/var/lib/postgresql/data # Named volume binded to Postgres' data store directory.

volumes:
  database-data:
    driver: local # Stores the volume data on the host machine's file system.

networks:
  playground-network:
    driver: "bridge"