export const apiFunctions = [
  {
    function: 'getRoles',
    description: 'Get all roles from integration.',
    param: '',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'getRole',
    description: 'Get role details.',
    param: 'roleName',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'getAzureIDIRUsers',
    description: 'Get user details.',
    param: '',
    query: {
      firstName: '',
      lastName: '',
      email: '',
      guid: '',
    },
    method: 'GET',
  },
  {
    function: 'getIDIRUsers',
    description: 'Get user details.',
    param: '',
    query: {
      firstName: '',
      lastName: '',
      email: '',
      guid: '',
    },
    method: 'GET',
  },
  {
    function: 'getGitHubBCGovUsers',
    description: 'Get user details.',
    param: '',
    query: {
      name: '',
      login: '',
      email: '',
      guid: '',
    },
    method: 'GET',
  },
  {
    function: 'getGitHubPublicUsers',
    description: 'Get user details.',
    param: '',
    query: {
      name: '',
      login: '',
      email: '',
      guid: '',
    },
    method: 'GET',
  },
  {
    function: 'getBasicBCeIDUsers',
    description: 'Get user details.',
    param: 'guid',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'getBusinessBCeIDUsers',
    description: 'Get user details.',
    param: 'guid',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'getBothBCeIDUsers',
    description: 'Get user details.',
    param: 'guid',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'createRole',
    description: 'Create a new role.',
    param: 'roleName',
    query: undefined,
    method: 'POST',
  },
  {
    function: 'deleteRole',
    description: 'Remove a role.',
    param: 'roleName',
    query: undefined,
    method: 'DELETE',
  },
  {
    function: 'updateRole',
    description: 'Rename a role.',
    param: 'roleName',
    query: { newRoleName: '' },
    method: 'PATCH',
  },
  {
    function: 'assignUserRole',
    description: 'Assign user a new role.',
    param: 'username',
    query: { role: '' },
    method: 'POST',
  },
  {
    function: 'unassignUserRole',
    description: 'Unassign a user role.',
    param: 'username',
    query: { role: '' },
    method: 'DELETE',
  },
  {
    function: 'getUserRoles',
    description: 'Get roles associated with a user.',
    param: 'username',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'getUsersWithRole',
    description: 'Get users associated with a role.',
    param: 'roleName',
    query: { page: 1, maxCount: 10 },
    method: 'GET',
  },
  {
    function: 'getRoleComposites',
    description: `Get a role's composites.`,
    param: 'roleName',
    query: undefined,
    method: 'GET',
  },
  {
    function: 'addRoleComposite',
    description: 'Add a composite to a role.',
    param: 'roleName',
    query: { newCompositeRoleName: '' },
    method: 'GET',
  },
  {
    function: 'deleteRoleComposite',
    description: 'Remove a composite role from a role.',
    param: 'roleName',
    query: { compositeRoleName: '' },
    method: 'GET',
  },
];
